import { deriveDetails, type PlayerDetails } from "@/lib/player-details";

export type PlayerStatus = "פעיל" | "ליגה בלבד" | "לא פעיל";

/** The roster columns held directly in the sample data. */
export interface PlayerBase {
  id: string;
  name: string;
  age: number;
  grade: string;
  israeliRating: number;
  fideRating: number | null;
  ratingUpdatedRecently: boolean;
  phone: string;
  clubs: string[];
  tournaments: string[];
  leagueTeam: string | null;
  status: PlayerStatus;
}

/** A full player record: roster columns plus the (invented) detail fields. */
export type Player = PlayerBase & PlayerDetails & { ratingUpdatedAt: string };

// "Today" for the mock data, used to place the rating-update dates relative to now.
const RATING_TODAY = new Date(2026, 5, 16);

/**
 * Mock "rating last updated" date per player (dd.MM.yyyy). Players flagged as
 * recently updated land within the last month (shown green); the rest land
 * over a month ago (shown red) — deterministic so the table stays stable.
 */
function ratingUpdatedDate(p: PlayerBase): string {
  const hash = [...p.id].reduce((acc, c) => acc + c.charCodeAt(0), 0);
  const daysAgo = p.ratingUpdatedRecently ? 1 + (hash % 25) : 40 + (hash % 160);
  const d = new Date(RATING_TODAY);
  d.setDate(d.getDate() - daysAgo);
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  return `${dd}.${mm}.${d.getFullYear()}`;
}

const basePlayers: PlayerBase[] = [
  {
    id: "p-1",
    name: "אורי גולן",
    age: 11,
    grade: "כיתה ו",
    israeliRating: 600,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-5555555",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-2",
    name: "יובל דוד",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 750,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "054-7777777",
    clubs: ["שחמט מתחילים"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-3",
    name: "ליאור ברק",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1450,
    fideRating: 1380,
    ratingUpdatedRecently: true,
    phone: "053-8888888",
    clubs: ["שחמט מתקדמים"],
    tournaments: [],
    leagueTeam: "רגלי החייל",
    status: "ליגה בלבד",
  },
  {
    id: "p-4",
    name: "מיה שפירא",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1650,
    fideRating: 1590,
    ratingUpdatedRecently: true,
    phone: "053-4444444",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-5",
    name: "נועם כץ",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 850,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "050-1111111",
    clubs: ["שחמט מתחילים", "מועדון אחה״צ"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "לא פעיל",
  },
  {
    id: "p-6",
    name: "נטע חיים",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 980,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-9999999",
    clubs: ["שחמט מתחילים", "מועדון אחה״צ"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-7",
    name: "עידן פרץ",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1100,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "054-3333333",
    clubs: ["שחמט מתקדמים", "אימון קבוצתי"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "ליגה בלבד",
  },
  {
    id: "p-8",
    name: "רון סעדון",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1750,
    fideRating: 1700,
    ratingUpdatedRecently: false,
    phone: "052-0000001",
    clubs: ["שחמט מתקדמים"],
    tournaments: [],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-9",
    name: "שיר מזרחי",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1350,
    fideRating: 1290,
    ratingUpdatedRecently: true,
    phone: "052-2222222",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "רגלי החייל",
    status: "פעיל",
  },
  {
    id: "p-10",
    name: "תמר אברהם",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1900,
    fideRating: 1850,
    ratingUpdatedRecently: true,
    phone: "052-6666666",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-11",
    name: "איתי לוי",
    age: 10,
    grade: "כיתה ה",
    israeliRating: 520,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "050-1212121",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-12",
    name: "דניאל כהן",
    age: 12,
    grade: "כיתה ז",
    israeliRating: 880,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "054-1313131",
    clubs: ["שחמט מתחילים", "מועדון אחה״צ"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-13",
    name: "אלון גרין",
    age: 17,
    grade: "כיתה יב",
    israeliRating: 2050,
    fideRating: 1980,
    ratingUpdatedRecently: true,
    phone: "052-1414141",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-14",
    name: "רוני בן דוד",
    age: 9,
    grade: "כיתה ד",
    israeliRating: 410,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "053-1515151",
    clubs: ["שחמט מתחילים"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-15",
    name: "עומר אזולאי",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1220,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "054-1616161",
    clubs: ["שחמט מתקדמים", "אימון קבוצתי"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: "רגלי החייל",
    status: "ליגה בלבד",
  },
  {
    id: "p-16",
    name: "יערה פלד",
    age: 11,
    grade: "כיתה ו",
    israeliRating: 640,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-1717171",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-17",
    name: "גיל אבני",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1480,
    fideRating: 1420,
    ratingUpdatedRecently: false,
    phone: "052-1818181",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "רגלי החייל",
    status: "פעיל",
  },
  {
    id: "p-18",
    name: "הילה רוזן",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 920,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "053-1919191",
    clubs: ["מועדון אחה״צ"],
    tournaments: [],
    leagueTeam: null,
    status: "לא פעיל",
  },
  {
    id: "p-19",
    name: "נדב שמש",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1820,
    fideRating: 1770,
    ratingUpdatedRecently: true,
    phone: "054-2020202",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-20",
    name: "מאיה הרשקוביץ",
    age: 12,
    grade: "כיתה ז",
    israeliRating: 720,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "050-2121212",
    clubs: ["שחמט מתחילים", "מועדון אחה״צ"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-21",
    name: "תום שטרן",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1310,
    fideRating: 1250,
    ratingUpdatedRecently: true,
    phone: "052-2323232",
    clubs: ["שחמט מתקדמים"],
    tournaments: [],
    leagueTeam: "רגלי החייל",
    status: "ליגה בלבד",
  },
  {
    id: "p-22",
    name: "אביב מור",
    age: 10,
    grade: "כיתה ה",
    israeliRating: 480,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "053-2424242",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-23",
    name: "ירדן פרידמן",
    age: 17,
    grade: "כיתה יב",
    israeliRating: 1960,
    fideRating: 1910,
    ratingUpdatedRecently: false,
    phone: "054-2525252",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-24",
    name: "שחר לביא",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 1010,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-2626262",
    clubs: ["שחמט מתחילים"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-25",
    name: "אריאל נחום",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1570,
    fideRating: 1510,
    ratingUpdatedRecently: true,
    phone: "052-2727272",
    clubs: [
      "שחמט מתקדמים",
      "אימון קבוצתי",
      "סדנת פתיחות",
      "קמפ אינטנסיבי",
      "הכנה לתחרויות",
    ],
    tournaments: [
      "גביע הנוער",
      "טורניר בית הספר",
      "אליפות הקיץ",
      "גביע האלופים",
      "ליגת הנוער",
    ],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-26",
    name: "בן ציון אליהו",
    age: 11,
    grade: "כיתה ו",
    israeliRating: 590,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "053-2828282",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "לא פעיל",
  },
  {
    id: "p-27",
    name: "ליה בכר",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1180,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "054-2929292",
    clubs: ["שחמט מתקדמים"],
    tournaments: [],
    leagueTeam: "רגלי החייל",
    status: "ליגה בלבד",
  },
  {
    id: "p-28",
    name: "עדן רביב",
    age: 12,
    grade: "כיתה ז",
    israeliRating: 810,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-3030303",
    clubs: ["מועדון אחה״צ"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-29",
    name: "יונתן ברגר",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1780,
    fideRating: 1720,
    ratingUpdatedRecently: false,
    phone: "052-3131313",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-30",
    name: "אסף וקנין",
    age: 5,
    grade: "גן",
    israeliRating: 380,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "053-3232323",
    clubs: ["שחמט מתחילים"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-31",
    name: "נעה דהן",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 950,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "054-3333334",
    clubs: ["שחמט מתחילים", "מועדון אחה״צ"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-32",
    name: "רועי שלום",
    age: 28,
    grade: "מבוגר",
    israeliRating: 2120,
    fideRating: 2070,
    ratingUpdatedRecently: false,
    phone: "050-3434343",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-33",
    name: "שני אדרי",
    age: 11,
    grade: "כיתה ו",
    israeliRating: 660,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "052-3535353",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-34",
    name: "מתן יוסף",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1520,
    fideRating: 1460,
    ratingUpdatedRecently: true,
    phone: "053-3636363",
    clubs: ["שחמט מתקדמים", "אימון קבוצתי"],
    tournaments: [],
    leagueTeam: "רגלי החייל",
    status: "ליגה בלבד",
  },
  {
    id: "p-35",
    name: "אופיר חדד",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1260,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "054-3737373",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-36",
    name: "טליה מלכה",
    age: 10,
    grade: "כיתה ה",
    israeliRating: 440,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-3838383",
    clubs: ["שחמט מתחילים"],
    tournaments: [],
    leagueTeam: null,
    status: "לא פעיל",
  },
  {
    id: "p-37",
    name: "אדם זילבר",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1860,
    fideRating: 1810,
    ratingUpdatedRecently: true,
    phone: "052-3939393",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-38",
    name: "אלה גבאי",
    age: 12,
    grade: "כיתה ז",
    israeliRating: 770,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "053-4040404",
    clubs: ["מועדון אחה״צ"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-39",
    name: "יהונתן אסולין",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1610,
    fideRating: 1550,
    ratingUpdatedRecently: true,
    phone: "054-4141414",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-40",
    name: "רעות סבן",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 890,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-4242424",
    clubs: ["שחמט מתחילים", "מועדון אחה״צ"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-41",
    name: "אורן טל",
    age: 24,
    grade: "מבוגר",
    israeliRating: 2010,
    fideRating: 1960,
    ratingUpdatedRecently: false,
    phone: "052-4343434",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-42",
    name: "מעיין שביט",
    age: 11,
    grade: "כיתה ו",
    israeliRating: 570,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "053-4444445",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-43",
    name: "אביתר רחמים",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1340,
    fideRating: 1280,
    ratingUpdatedRecently: true,
    phone: "054-4545454",
    clubs: ["שחמט מתקדמים", "אימון קבוצתי"],
    tournaments: [],
    leagueTeam: "רגלי החייל",
    status: "ליגה בלבד",
  },
  {
    id: "p-44",
    name: "כרמל פינטו",
    age: 6,
    grade: "גן",
    israeliRating: 360,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "050-4646464",
    clubs: ["שחמט מתחילים"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-45",
    name: "אורי בר",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1720,
    fideRating: 1670,
    ratingUpdatedRecently: true,
    phone: "052-4747474",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-46",
    name: "טל אוחנה",
    age: 12,
    grade: "כיתה ז",
    israeliRating: 740,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "053-4848484",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "לא פעיל",
  },
  {
    id: "p-47",
    name: "יסמין לוין",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1430,
    fideRating: 1370,
    ratingUpdatedRecently: false,
    phone: "054-4949494",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "רגלי החייל",
    status: "פעיל",
  },
  {
    id: "p-48",
    name: "נריה כהן",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 870,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-5050505",
    clubs: ["מועדון אחה״צ"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-49",
    name: "אביגיל סטולר",
    age: 17,
    grade: "כיתה יב",
    israeliRating: 1940,
    fideRating: 1890,
    ratingUpdatedRecently: true,
    phone: "052-5151515",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-50",
    name: "יהלי שרון",
    age: 10,
    grade: "כיתה ה",
    israeliRating: 500,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "053-5252525",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-51",
    name: "עידו בן חמו",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1290,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "054-5353535",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: "רגלי החייל",
    status: "ליגה בלבד",
  },
  {
    id: "p-52",
    name: "ספיר טוויל",
    age: 11,
    grade: "כיתה ו",
    israeliRating: 620,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "050-5454545",
    clubs: ["שחמט מתחילים", "מועדון אחה״צ"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-53",
    name: "אילן פוקס",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1800,
    fideRating: 1740,
    ratingUpdatedRecently: false,
    phone: "052-5555556",
    clubs: ["שחמט מתקדמים", "אימון קבוצתי"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-54",
    name: "נויה ביטון",
    age: 13,
    grade: "כיתה ח",
    israeliRating: 940,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "053-5656565",
    clubs: ["שחמט מתחילים"],
    tournaments: [],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-55",
    name: "אסיף לוגסי",
    age: 15,
    grade: "כיתה י",
    israeliRating: 1540,
    fideRating: 1480,
    ratingUpdatedRecently: true,
    phone: "054-5757575",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "רגלי החייל",
    status: "פעיל",
  },
  {
    id: "p-56",
    name: "רותם ארביב",
    age: 9,
    grade: "כיתה ד",
    israeliRating: 400,
    fideRating: null,
    ratingUpdatedRecently: false,
    phone: "050-5858585",
    clubs: ["שחמט מתחילים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-57",
    name: "אופק שמואל",
    age: 12,
    grade: "כיתה ז",
    israeliRating: 790,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "052-5959595",
    clubs: ["מועדון אחה״צ"],
    tournaments: [],
    leagueTeam: null,
    status: "לא פעיל",
  },
  {
    id: "p-58",
    name: "הדר אלבז",
    age: 14,
    grade: "כיתה ט",
    israeliRating: 1160,
    fideRating: null,
    ratingUpdatedRecently: true,
    phone: "053-6060606",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["טורניר בית הספר"],
    leagueTeam: null,
    status: "פעיל",
  },
  {
    id: "p-59",
    name: "ניר אטיאס",
    age: 17,
    grade: "כיתה יב",
    israeliRating: 2080,
    fideRating: 2030,
    ratingUpdatedRecently: false,
    phone: "054-6161616",
    clubs: ["שחמט מתקדמים"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
  {
    id: "p-60",
    name: "מיכל אדלר",
    age: 16,
    grade: "כיתה יא",
    israeliRating: 1700,
    fideRating: 1650,
    ratingUpdatedRecently: true,
    phone: "050-6262626",
    clubs: ["שחמט מתקדמים", "אימון קבוצתי"],
    tournaments: ["גביע הנוער"],
    leagueTeam: "אריות צעירים",
    status: "פעיל",
  },
];

/** The roster as full player records, each enriched with invented details. */
export const players: Player[] = basePlayers.map((p) => ({
  ...p,
  ...deriveDetails(p),
  ratingUpdatedAt: ratingUpdatedDate(p),
}));

export const allClubs = Array.from(
  new Set(players.flatMap((p) => p.clubs)),
).sort((a, b) => a.localeCompare(b, "he"));

export const allGrades = Array.from(new Set(players.map((p) => p.grade))).sort(
  (a, b) => a.localeCompare(b, "he"),
);

export const allStatuses: PlayerStatus[] = ["פעיל", "ליגה בלבד", "לא פעיל"];
